// ignore_for_file: file_names, constant_identifier_names

const fluidos = [
  ['AF', 'antiespumante'],
  ['AFL', 'flare de gas acido'],
  ['AG', 'gas acido'],
  ['BW', 'agua de calentamiento'],
  ['CD', 'drenaje frío'],
  ['CF', 'flare frío'],
  ['CH', 'inyección química'],
  ['CN', 'condensado'],
  ['CW', 'agua de enfriamiento'],
  ['DN', 'drenaje de servicio no presurizado'],
  ['DO', 'diesel oil'],
  ['DR', 'drenaje cerrado'],
  ['DW', 'agua potable'],
  ['ET', 'etanol'],
  ['FG', 'fuel gas'],
  ['FL', 'flare'],
  ['FM', 'espuma contra incendios'],
  ['FO', 'fuel oil'],
  ['FW', 'agua de incendios'],
  ['GD', 'drenaje de glicol'],
  ['GL', 'glicol'],
  ['GS', 'gas servicio'],
  ['HAD', 'drenaje de aminas a alta presión'],
  ['HG', 'hidrocarburo gaseoso'],
  ['HL', 'hidrocarburo líquido'],
  ['HO', 'hot oil '],
  ['HPS', 'vapor de alta presión'],
  ['AI', 'aire de instrumentos'],
  ['IG', 'gas de instrumentos '],
  ['IW', 'agua de inyección'],
  ['SPA', 'amina pobre'],
  ['LAD', 'drenaje de aminas a baja presión'],
  ['LO', 'aceite'],
  ['LPS', 'vapor de baja presión'],
  ['ME', 'metanol'],
  ['MPS', 'vapor de media presión'],
  ['MUA', 'amina de reposición'],
  ['N', 'nitrógeno'],
  ['NN', 'drenaje de proceso no presurizado'],
  ['OD', 'drenaje abierto'],
  ['PD', 'drenaje pluvial contaminado'],
  ['PE', 'petróleo'],
  ['PL', 'propano líquido'],
  ['PV', 'propano vapor'],
  ['PW', 'agua de proceso'],
  ['SRA', 'amina rica'],
  ['RW', 'agua no tratada'],
  ['SA', 'aire de arranque'],
  ['SAG', 'vapor y gas ácido'],
  ['SF', 'flare de gas ácido'],
  ['SG', 'gas de arranque'],
  ['ST', 'vapor'],
  ['STG', 'gas dulce'],
  ['SW', 'agua de mar'],
  ['TW', 'agua tratada'],
  ['UA', 'aire de servicio'],
  ['UW', 'agua de servicio'],
  ['VG', 'gas de venteo'],
  ['WP', 'agua de proceso'],
  ['WR', 'agua del reciclo'],
  ['WW', 'agua residual'],
]; //revisar

const codYacimiento = [
  ['AGA01', 'cerro dragon/ distrito 1'],
  ['AGB01', 'cerro dragon/distrito 2'],
  ['AGB02', 'cerro dragon/ distrito 3'],
]; // yy zzz todo junto

const NdeArea = [
  ['10', 'ingreso a planta'],
  ['11', 'ingreso a planta'],
  ['15', 'ingreso a planta'],
  ['20', 'separador primario'],
  ['21', 'separador primario'],
  ['22', 'separador primario'],
  ['23', 'separador primario'],
  ['24', 'separador primario'],
  ['25', 'separador primario'],
  ['29', 'separador primario'],
  ['30', 'tratamiento de petroleo'],
  ['36', 'tratamiento de petroleo'],
  ['37', 'tratamiento de petroleo'],
  ['38', 'tratamiento de petroleo'],
  ['39', 'tratamiento de petroleo'],
  ['40', 'tratamiento de agua'],
  ['47', 'tratamiento de agua'],
  ['48', 'tratamiento de agua'],
  ['49', 'tratamiento de agua'],
  ['50', 'tratamiento de gas y servicios auxiliares'],
  ['51', 'tratamiento de gas y servicios auxiliares'],
  ['56', 'tratamiento de gas y servicios auxiliares'],
  ['57', 'tratamiento de gas y servicios auxiliares'],
  ['58', 'tratamiento de gas y servicios auxiliares'],
  ['59', 'tratamiento de gas y servicios auxiliares'],
  ['60', 'sistemas de agua'],
  ['68', 'sistemas de agua'],
  ['69', 'sistemas de agua'],
  ['70', 'drenajes, venteos, reprocesos'],
  ['77', 'drenajes, venteos, reprocesos'],
  ['78', 'drenajes, venteos, reprocesos'],
  ['79', 'drenajes, venteos, reprocesos'],
  ['80', 'compresion'],
  ['85', 'compresion'],
  ['86', 'compresion'],
  ['87', 'compresion'],
  ['88', 'compresion'],
  ['90', 'manifold auxiliar'],
  ['95', 'manifold auxiliar'],
];

const NdeLineaCorrelativo = [
  ['10', 'gato'],
  ['11', 'perro'],
  ['15', 'cerdo'],
]; //no se usa

const ClasedeCaneria = [
  ['PA4', 'anticongelante'],
  ['PA12', 'hidrocarburos'],
  ['PA25', 'agua dulce'],
  ['CA20', ''],
  ['QA20', ''],
  ['VA20', ''],
  ['CB20', ''],
  ['CC20', ''],
  ['QB20', ''],
  ['SD16', ''],
  ['PF10', ''],
  ['GA20', ''],
  ['CA40', ''],
  ['QA40', ''],
  ['VA40', ''],
  ['CB40', ''],
  ['QB40', ''],
  ['VB40', ''],
  ['CC40', ''],
  ['CB50', ''],
  ['SD60', ''],
  ['CA80', ''],
  ['QA80', ''],
  ['WA80', ''],
  ['CB80', ''],
  ['QB80', ''],
  ['VB80', ''],
  ['CA100', ''],
  ['QA100', ''],
  ['CB100', ''],
  ['QB100', ''],
  ['CC100', ''],
  ['SD100', ''],
  ['CB150', ''],
  ['QB150', ''],
  ['CC150', ''],
  ['VC150', ''],
  ['CB160', ''],
  ['VC160', ''],
  ['CC70', ''],
  ['CB230', ''],
  ['QB230', ''],
  ['CB260', 'agua de formacion'],
  ['QB260', 'agua de formacion'],
  ['CC380', 'hidrocarburo gaseoso'],
];

const Aislacion = [
  ['B', 'sin aislacion'],
  ['C', 'aislacion por frio'],
  ['E', 'aislacion y tracing electrico'],
  ['H', 'aislacion por calor'],
  ['P', 'proteccion personal'],
]; //bien

const equipos = [
  ['A', 'aeroenfriadores'],
  ['AT', 'torre de absorción'],
  ['B', 'ventiladores y sopladores'],
  ['BO', 'calderas'],
  ['CT', 'torres de enfriamiento'],
  ['CS', 'columna de stripping'],
  ['D', 'deshidratadores'],
  ['DB', 'playa secado'],
  ['DG', 'desgasificadores'],
  ['E', 'intercambiadores de calor'],
  ['F', 'filtros'],
  ['FT', 'tanque flash'],
  ['G', 'generador electrico'],
  ['H', 'hornos'],
  ['HE', 'calentador eléctrico'],
  ['K', 'compresor'],
  ['L', 'antorchas'],
  ['LA', 'brazo de carga'],
  ['ME', 'motor eléctrico'],
  ['MD', 'motor diesel'],
  ['MG', 'motor a gas'],
  ['MO', 'módulo'],
  ['MX', 'agitador'],
  ['P', 'bomba'],
  ['PE', 'pileta de emergencia'],
  ['PQ', 'paquete inyección químicos'],
  ['PS', 'equipo separador de fases'],
  ['R', 'reactor'],
  ['RE', 'reboiler'],
  ['RT', 'torre de regeneración'],
  ['S', 'secador'],
  ['SC', 'contactor secundario'],
  ['SE', 'separador'],
  ['SP', 'trampa de scrapper'],
  ['ST', 'silenciadores'],
  ['T', 'torres y columnas'],
  ['TC', 'tratador termoeléctroestático'],
  ['TG', 'turbina de gas'],
  ['TK', 'tanque'],
  ['TV', 'turbina de vapor'],
  ['X', 'expansor'],
  ['V', 'recipientes'],
]; //revisar

const tipodevalvula = [
  ['B', 'esferica'],
  ['C', 'cuatro vias'],
  ['E', 'esclusa'],
  ['F', 'esferica paso total'],
  ['G', 'globo'],
  ['H', 'diafragma'],
  ['K', 'cuchilla'],
  ['M', 'mariposa'],
  ['N', 'aguja'],
  ['P', 'tapon'],
  ['R', 'retencion'],
  ['S', 'tipo rising stem'],
  ['T', 'tres vias'],
]; //bien

const tipoextremo = [
  ['B', 'soldadura a tope'],
  ['F', 'bridada'],
  ['L', 'entre bridas tipo lug'],
  ['R', 'roscada'],
  ['S', 'soldadura a enchufe'],
  ['W', 'entre bridas tipo wafer'],
]; //bien

const accesorrios = [
  ['E', 'con vastago extendido'],
  ['L', 'con traba candado'],
  ['Y', 'con vastago extendido y traba candado'],
  ['X', 'fire safe'],
]; //bien

const abreviaturasGenerales = [
  ['A/G', 'sobre nivel del terreno'],
  ['ATM', 'atmosferico'],
  ['BDV', 'venteo de emergencia'],
  ['CC', 'cupon de corrosion'],
  ['CP', 'probeta'],
  ['FC', 'falla cerrada'],
  ['FO', 'falla abierta'],
  ['FL', 'falla ultima posicion'],
  ['IQ', 'inyeccion de quimicos'],
  ['LS', 'fire safe'],
  ['LO', 'traba abierta'],
  ['LC', 'traba cerrada'],
  ['NC', 'normal cerrada'],
  ['NO', 'normal abierta'],
  ['NNF', 'normalmente no flujo'],
  ['SC', 'toma de muestra'],
  ['U/G', 'enterrado'],
];

const letra1 = [
  ['A', 'analisis'],
  ['B', 'quemador'],
  ['C', 'corrosion'],
  ['D', 'eleccion de usuario'],
  ['E', 'voltaje'],
  ['T', 'temperatura'],
];

const letra2 = [
  ['A', 'alarma'],
  ['B', 'eleccion de ususario'],
  ['C', 'control'],
  ['D', 'nada'],
  ['E', 'sensor(elemento primario)'],
  ['I', 'indicador'],
];
